# Question 1:

In [6]:
import numpy as num
array = num.arange(2,50,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2:

In [13]:
import numpy as num
list1 = []
list2 = []
print("Enter items in list1: ")
for i in range(5):
    p = int(input())
    list1.append(p)
print(list1)
print("Enter items in list2: ")
for i in range(5):
    p = int(input())
    list2.append(p)
print(list2)
array = num.array([list1, list2])
print(array)
array = array.reshape(1,10)
array = num.sort(array)
array = array.reshape(1,10)
print(array)

Enter items in list1: 
1
0
2
3
4
[1, 0, 2, 3, 4]
Enter items in list2: 
9
1
0
8
7
[9, 1, 0, 8, 7]
[[1 0 2 3 4]
 [9 1 0 8 7]]
[[0 0 1 1 2 3 4 7 8 9]]


# Question 3:

In [32]:
import numpy as num
arr = num.array([[1,2,3],[4,5,6],[7,8,9]])
print("Number of dimensions: " ,arr.ndim)
print("Shape of array: " ,arr.shape)
print("Type of array: " ,type(arr))
print("Size of array: " ,arr.size)

Number of dimensions:  2
Shape of array:  (3, 3)
Type of array:  <class 'numpy.ndarray'>
Size of array:  9


# Question 4:

In [46]:
import numpy as num
arr = num.array([1,2,3,4])
print(arr)
arr = arr.reshape(2,2)
print(arr)

[1 2 3 4]
[[1 2]
 [3 4]]


# Question 5:

In [61]:
import numpy as num
arr1 = num.array([[1,6,4], [8,6,4]])
arr2 = num.array([[6,0,9], [3,5,9]])
print("Vertical stack:\n " ,num.vstack((arr1,arr2)))
print("Horizontal stack: \n" ,num.hstack((arr1,arr2)))

Vertical stack:
  [[1 6 4]
 [8 6 4]
 [6 0 9]
 [3 5 9]]
Horizontal stack: 
 [[1 6 4 6 0 9]
 [8 6 4 3 5 9]]


# Question 6:

In [62]:
import numpy as num
num_list = num.array([1,2,2,1,3,4,5,3])
(unique, counts) = num.unique(num_list, return_counts = True)
freq = num.asarray((unique, counts)).T
print(freq)

[[1 2]
 [2 2]
 [3 2]
 [4 1]
 [5 1]]
